### ISSUE TITLE
Cant get it to work...

### ISSUE THREAD

**Issue by RolfHahil** [markusdd/FilamentSamples#5]
Hey, i tried it but faild. i get this error:
Traceback (most recent call last):
  File "C:\Users\leand\gen_samples.py", line 37, in <module>
    gen_samples()
  File "C:\Users\leand\gen_samples.py", line 25, in gen_samples
    subprocess.run(
  File "C:\Users\leand\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leand\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\leand\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

can you tell me what im doing wrong?

**Comment by markusdd** [comment]
you do not have Openscad in your $PATH variable.

so when Python tries to call it, it fails.

**Comment by RolfHahil** [comment]
Thanks for the fast reply. I changed the path now but it still istn working. The following shows now:

_Processing: ['Bambu Lab', 'PLA Matte', 'Latte Brown', '220', '50']
Traceback (most recent call last):
  File "C:\Users\leand\gen_samples.py", line 37, in <module>
    gen_samples()
  File "C:\Users\leand\gen_samples.py", line 25, in gen_samples
    subprocess.run(
  File "C:\Users\leand\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Programme\\OpenSCAD\\openscad.exe', '-o', 'stl/Bambu Lab_PLA Matte_Latte Brown_220_50.stl', '-D', 'BRAND="Bambu Lab"', '-D', 'TYPE="PLA Matte"', '-D', 'COLOR="Latte Brown"', '-D', 'TEMP_HOTEND="220"', '-D', 'TEMP_BED="50"', 'C:\\Users\\leand/FilamentSamples.scad']' returned non-zero exit status 3._

**Comment by markusdd** [comment]
ok that means that OpenSCAD itself errors out because of something

Are you getting any additional output?

**Comment by RolfHahil** [comment]
By output you mean in cmd? No, nothing.

**Comment by markusdd** [comment]
how are you running the the tool? Are you doing it from within vs code, or on the commandline?

**Comment by RolfHahil** [comment]
![grafik](https://github.com/markusdd/FilamentSamples/assets/155472006/4b4c64cb-38f9-4514-9ecc-5e0473678a75)
With the commandline

**Comment by markusdd** [comment]
the path to the scad file somehow looks weird. are you in the directory where it is located?

**Comment by RolfHahil** [comment]
The gen_samples.py is located at C:\users\leand

The path on my computer shows as "C:\Programme\OpenScad" (german) thats why I changed the code to that direction. For testing I downloaded your file again with your code. This shows now:
![grafik](https://github.com/markusdd/FilamentSamples/assets/155472006/7613ab4a-2f28-4803-9097-79d0e12d2f5d)

**Comment by markusdd** [comment]
Is that also where the .scad file is located? Because according to that output it cannot find it there. You need more than the Python script, the FilementSamples.scad file also needs to be next to it.

**Comment by RolfHahil** [comment]
No, of course not... I didnt download it in the first place. Sorry for the trouble and thank you very much for the fast help!

Happy new year!

**Comment by markusdd** [comment]
haha, shit happens.

No problem, enjoy!
